### ISSUE TITLE
Chrome 商店地址

### ISSUE THREAD

**Issue by yangtzech** [shuzijun/leetcode-editor-extension#1]
你好，请问插件目前上架 Chrome 了，好像搜不到

**Comment by shuzijun** [comment]
上架的流程还没弄完，先通过https://github.com/shuzijun/leetcode-editor-extension/releases  下载zip，解压后通过源码安装一下。
安装步骤可以参考：https://docs.plasmo.com/workflows#loading-the-extension，目录选择zip解压之后的目录

**Comment by yangtzech** [comment]
好的
